services:
  emailservice:
    image: kshitiz182/emailservice:latest
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1

  checkoutservice:
    image: kshitiz182/checkoutservice:latest
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070

  recommendationservice:
    image: kshitiz182/recommendationservice:latest
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1

  frontend:
    image: kshitiz182/frontend:latest
    ports:
      - "81:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - DISABLE_PROFILER=1

  paymentservice:
    image: kshitiz182/paymentservice:latest
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  productcatalogservice:
    image: kshitiz182/productcatalogservice:latest
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1

  cartservice:
    image: kshitiz182/cartservice:latest
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379

  loadgenerator:
    image: kshitiz182/loadgenerator:latest
    environment:
      - FRONTEND_ADDR=frontend:80
      - USERS=10

  currencyservice:
    image: kshitiz182/currencyservice:latest
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1

  shippingservice:
    image: kshitiz182/shippingservice:latest
    ports:
      - "50052:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  redis-cart:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  adservice:
    image: kshitiz182/adservice:latest
    ports:
      - "9555:9555"
    environment:
      - PORT=9555

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - emailservice
      - checkoutservice
      - recommendationservice
      - paymentservice
      - productcatalogservice
      - cartservice
      - currencyservice
      - shippingservice
      - adservice      

volumes:
  redis-data:
