#server {
#    listen 80;
#    listen [::]:80;

#    server_name 192.168.19.12;

#    ssl_certificate /home/vagrant/repo/nginx-ssl-cert/nginx-selfsigned.cert;
#    ssl_certificate_key /home/vagrant/repo/nginx-ssl-cert/nginx-selfsigned.key;

#    location / {
#        proxy_pass http://localhost:81;  # docker-compose (online boutique)
#    }
#    location / {
#        proxy_pass http://192.168.19.12:31230;  # KIND cluster
#    }
#}


# -------------------------------------------------------------


user www-data;
worker_processes auto;

events {
worker_connections 1024;
}

http {

        include /etc/nginx/mime.types;

#       # gzip compression
#       gzip on;
#       gzip_comp_level 4;
#       gzip_types text/plain text/css text/xml text/javascript application/javascript application/json;

        server {

                listen 80; # listen 80 http2; (To switch from http1.1 to http2)
                listen [::]:80;
                server_name 192.168.19.12;

#               root /home/vagrant/online-boutique;

                location / {
#               location ~* \.(css|js|jpg|png|jpeg) # For caching
                        proxy_pass http://frontend:8080;
                        add_header Cache-Control public;
                        add_header Pragma public;
                        add_header Vary Accept-Encoding;
                        expires 3M;
                }

        }
}
