server {

        listen 80; # listen 80 http2; (To switch from http1.1 to http2)
        server_name 192.168.19.11;

        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;

        }

server {

        listen 443 ssl;
        server_name 192.168.19.11;

        server_tokens off;

        ssl_certificate /etc/nginx/nginx-selfsigned.cert;
        ssl_certificate_key /etc/nginx/nginx-selfsigned.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        # Security Headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

        location / {
                proxy_pass http://frontend:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                }

        }
